# _config.yml
title: My Advanced GitHub Page
description: This is my advanced personal website.
url: "https://username.github.io"
baseurl: "/my-repo" # Hanya jika repository Anda bukan di root

# Tema dan Kustomisasi
theme: minima

# Pengaturan Permalink
permalink: /:categories/:year/:month/:day/:title/

# Markdown dan Highlighter
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Plugin
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pengaturan Build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Kustomisasi Data
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"

# Pengaturan SEO
seo:
  title: "My Advanced GitHub Page"
  description: "This is my advanced personal website."
  url: "https://username.github.io"
  twitter: username
  facebook:
    admins: username
